image: docker:latest

stages:
    - build

build:
    stage: build
    script:
        - VERSION=$(docker build -t "corysanin/clone-hero-server:latest" . | grep "Game Version:" | awk "s/Game Version: //")
        - docker build -t "corysanin/clone-hero-server:$VERSION" .
        - docker push "corysanin/clone-hero-server:$VERSION"
        - docker push "corysanin/clone-hero-server:latest"