version: '3'
services:
  clone-hero-server:
    build:
      context: .
    ports:
      - "127.0.0.1:14242:14242"
    volumes:
      - ./config:/usr/src/clonehero/config
    container_name: clone-hero-server
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped
